services:
  app:
    build: .
    container_name: "voice_transcribe"
    env_file:
      - .env
    ports:
      - 8081:8081
    networks:
      - ntwrk  
    environment:
      - TZ=Asia/Tashkent
    depends_on:
      vcdb:
        condition: service_started
      minio:
        condition: service_started
  minio:
    image: minio/minio
    container_name: miniooo
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
    ports:
      - "9003:9003"   
      - "9002:9002" 
    command: server /data --console-address ":9002"
    # volumes:
    #   - minio_data:/data
    networks:
      - ntwrk
  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - ntwrk

  vcdb:
    image: postgres:latest
    container_name: vcdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mirxonjon
      POSTGRES_DB: voice_transcribe
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ntwrk
  migrate:
    image: migrate/migrate
    depends_on:
      - vcdb
    volumes:
      - ./migrations:/migrations
    entrypoint: ["/bin/sh", "-c"]
    command: >
      sleep 5 &&
      migrate -path=/migrations -database=${PG_URL} up
    environment:
      - DATABASE_URL=${PG_URL}

networks:
  ntwrk: 
    external: true


volumes:
  postgres_data:
    driver: local
  # minio_data:
  #   driver: local
