services:
  app:
    build: .
    container_name: "voice_transcribe"
    volumes:
      - ./internal/media:/app/internal/media 
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - ntwrk  
    depends_on:
      vcdb:
        condition: service_started

  
  vcdb:
    image: postgres:latest
    container_name: vcdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: voice_transcribe
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ntwrk

networks:
  ntwrk: 
    external: true


volumes:
  postgres_data:
    driver: local
