services:
  app:
    build: .
    container_name: "voice_transcribe"
    volumes:
      - ./internal/media:/app/internal/media 
      - ./internal/media/audio:/app/internal/media/audio
      - ./internal/media/segments:/app/internal/media/segments
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - ntwrk  
    depends_on:
      vcdb:
        condition: service_started
      minio:
        condition: service_started
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_ENDPOINT=minio:9000
    ports:
      - "9000:9000"   
      - "9001:9001" 
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - ntwrk
  
  vcdb:
    image: postgres:latest
    container_name: vcdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: voice_transcribe
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ntwrk

networks:
  ntwrk: 
    external: true


volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
