basePath: /
definitions:
  entity.AudioSegment:
    properties:
      audio_id:
        type: integer
      audio_name:
        type: string
      created_at:
        type: string
      file_path:
        type: string
      id:
        type: integer
      status:
        type: string
    type: object
  entity.AudioSegmentList:
    properties:
      audio_segments:
        items:
          $ref: '#/definitions/entity.AudioSegment'
        type: array
      count:
        type: integer
    type: object
  entity.ErrorResponse:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  entity.LoginReq:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  entity.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  entity.Transcript:
    properties:
      ai_text:
        type: string
      audio_id:
        type: integer
      audio_name:
        type: string
      created_at:
        type: string
      id:
        type: integer
      report_text:
        type: string
      segment_id:
        type: integer
      status:
        type: string
      transcribe_text:
        type: string
      user_id:
        type: string
      username:
        type: string
    type: object
  entity.TranscriptList:
    properties:
      count:
        type: integer
      transcripts:
        items:
          $ref: '#/definitions/entity.Transcript'
        type: array
    type: object
  entity.TranscriptPersent:
    properties:
      audio_file_id:
        type: integer
      completed_segments:
        type: integer
      filename:
        type: string
      percent:
        type: number
      total_segments:
        type: integer
    type: object
  entity.UpdateTranscriptBody:
    properties:
      report_text:
        type: string
      transcribe_text:
        type: string
    type: object
  entity.UserInfo:
    properties:
      agent_id:
        type: string
      create_date:
        type: string
      first_number:
        type: string
      image:
        type: string
      login:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
      service_name:
        type: string
    type: object
  entity.UserTranscriptStatictics:
    properties:
      daily_chunks:
        type: string
      total_audio_files:
        type: integer
      total_chunks:
        type: integer
      total_minutes:
        type: number
      username:
        type: string
      weekly_audio_files:
        type: integer
      weekly_chunks:
        type: integer
    type: object
info:
  contact: {}
  description: This is a sample server Voice Transcribe server.
  title: Voice Transcribe API
  version: "1.0"
paths:
  /api/v1/audio_segment:
    get:
      consumes:
      - application/json
      description: Get a list of audio_segment
      parameters:
      - description: Filter by audio id
        in: query
        name: audio_id
        type: integer
      - description: Filter by status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.AudioSegmentList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a list of audio_segment
      tags:
      - audio_segment
  /api/v1/audio_segment/{id}:
    get:
      consumes:
      - application/json
      description: Get a audio_segment by ID
      parameters:
      - description: AudioSegment ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.AudioSegment'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a audio_segment by ID
      tags:
      - audio_segment
  /api/v1/audio_segment/delete:
    delete:
      consumes:
      - application/json
      description: Delete a audio_segment
      parameters:
      - description: AudioSegment ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a audio_segment
      tags:
      - audio_segment
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: User
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/entity.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: Login
      tags:
      - auth
  /api/v1/auth/one:
    get:
      consumes:
      - application/json
      description: Get a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a user
      tags:
      - auth
  /api/v1/dashboard:
    get:
      consumes:
      - application/json
      description: Get a list of audio percent
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.TranscriptPersent'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a list of audio percent
      tags:
      - dashboard
  /api/v1/dashboard/user/{user_id}:
    get:
      consumes:
      - application/json
      description: Get the user dashboard
      parameters:
      - description: user id
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.UserTranscriptStatictics'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get the user dashboard
      tags:
      - dashboard
  /api/v1/transcript/{id}:
    get:
      consumes:
      - application/json
      description: Get a transcript by ID
      parameters:
      - description: Chunk ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Transcript'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a transcript by ID
      tags:
      - transcript
  /api/v1/transcript/delete:
    delete:
      consumes:
      - application/json
      description: Delete a transcript
      parameters:
      - description: Chunk ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Delete a transcript
      tags:
      - transcript
  /api/v1/transcript/list:
    get:
      consumes:
      - application/json
      description: Get a list of transcripts
      parameters:
      - description: Offset for pagination
        in: query
        name: offset
        type: number
      - description: Limit for pagination
        in: query
        name: limit
        type: number
      - description: Filter by audio id
        in: query
        name: audio_id
        type: integer
      - description: Filter by user id
        in: query
        name: user_id
        type: integer
      - description: Filter by status
        in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.TranscriptList'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get a list of transcripts
      tags:
      - transcript
  /api/v1/transcript/update:
    put:
      consumes:
      - application/json
      description: Update a transcript
      parameters:
      - description: Chunk ID
        in: query
        name: id
        required: true
        type: integer
      - description: Transcript object
        in: body
        name: transcript
        required: true
        schema:
          $ref: '#/definitions/entity.UpdateTranscriptBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Update a transcript
      tags:
      - transcript
  /api/v1/upload-zip-audio:
    post:
      consumes:
      - multipart/form-data
      description: Upload Zip file
      parameters:
      - description: Zip file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload Zip file
      tags:
      - audio
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
